### ISSUE TITLE
Problem getting a useable picture of IT8

### ISSUE THREAD

**Issue by saintger** [pmjdebruijn/colormatch#2]
Hello,

I'm trying to get an IT8 picture which comply to your specifications, but I haven't managed to get the correct values of GS0 and GS23 patch (see attached picture).
If I am above 97% for GS0, I am also really above 3% for GS23 (around 10-16%).
What am I doing wrong ?

![_dsc2609](https://cloud.githubusercontent.com/assets/1916284/16173214/71d1823c-359a-11e6-9c81-e7bda0420bb8.JPG)
![_dsc2612](https://cloud.githubusercontent.com/assets/1916284/16173216/793a55da-359a-11e6-89c3-29c043a0cef9.JPG)
![_dsc2613](https://cloud.githubusercontent.com/assets/1916284/16173219/8001f06c-359a-11e6-9624-4eafec673d25.JPG)

Thanks in advance,

**Comment by pmjdebruijn** [comment]
Just try to get the min and max value centered.

However, if the black patch is around 10-13% it sound you simply got the exposure wrong, did you do third stop exposure like the tutorial mentioned? If yes, then just try again on another day.

And this is a bug tracker, not a support forum. If you have question come by on IRC.
